## Refer to the FaceFormer to predict the expression parameters
checkpoint_dir: work_dir/train_face_3dmm_expression_mouth_mask
test_mode: False

model_name: Face3DMMOneHotFormer

checkpoint: null

max_epochs: 200
check_val_every_n_epoch: 1

lr: 0.0001
wd: 0.0
lr_decay_step: 20
lr_decay_rate: 0.8

dataset:
  dataset_name: Face3DMMOneHotDataset
  data_root: ./data/HDTF_preprocessed
  batch_size: 1
  fetch_length: 100
  fetch_stride: 100
  number_workers: 6

teacher_forcing: False

Face3DMMFormer:
  dataset: vocaset
  feature_dim: 1024
  period: 25
  vertice_dim: 64
  use_mouth_mask: True
