## A small version for training GSmoothFace in small dataset.
exp_name: full_model

log_dir: work_dir/train_one_hot_3dmmformer
test_mode: False

checkpoint: null

model_name: Face3DMMOneHotFormer

trainer:
  max_epochs: 20 # 120
  check_val_every_n_epoch: 1
  val_check_interval: 0.5 # [0.0, 1.0]

vis_step: 250

lr: 0.0001
wd: 0.0
lr_decay_step: 20
lr_decay_rate: 0.8

dataset:
  batch_size: 1
  number_workers: 6

  train:
    type: Face3DMMOneHotDataset
    params:
      data_root: ./data/HDTF_face3dmmformer
      split: data/HDTF_face3dmmformer/train.txt
      fetch_length: 100
      fetch_stride: 100
      use_template_face: False

    dataloader_params:
      batch_size: 1
      shuffle: True
      num_workers: 6
  val:
    type: Face3DMMOneHotDataset
    params:
      data_root: ./data/HDTF_face3dmmformer
      split: data/HDTF_face3dmmformer/val.txt
      fetch_length: 100
      fetch_stride: 100
      use_template_face: False
    
    dataloader_params:
      batch_size: 1
      shuffle: False
      num_workers: 6

  # audio_path: data/HDTF_preprocessed/WRA_KristiNoem0_000/WRA_KristiNoem0_000.wav
  audio_path: data/audio_samples/Silence.wav
  video_name: train/WDA_ChrisMurphy0_000
  training_split: train

teacher_forcing: False
supervise_exp: False

Face3DMMFormer:
  dataset: vocaset
  feature_dim: 1024
  period: 25
  num_speakers: 8 # for one-hot identities embedding
  vertice_dim: 64
  use_mouth_mask: True
